# Generated by Django 5.1.4 on 2024-12-15 06:49
from django.db import migrations

def delete_some_records(apps, schema_editor):
    # Get the model
    Employee = apps.get_model('api', 'Employee')

    # Filter and delete records based on your condition
    # Example: Keep records with specific IDs
    excluded_ids = [2,12]  # IDs of records you want to keep
    Employee.objects.exclude(id__in=excluded_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RunPython(delete_some_records),
    ]



   
